# collect the latest price of each shoes

import urllib.request
import bs4
import ssl
import pandas as pd
import re


# format the list of url based on the number of page
urls = ['https://stockx.com/sneakers?page={}'.format(i)
        for i in range(1, 26)]
# for each page read the name of the shoes
name = []
for url in urls:
    ssl._create_default_https_context = ssl._create_unverified_context
    headers = {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) '
                      'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'}
    req = urllib.request.Request(url=url, headers=headers)
    response = urllib.request.urlopen(req)
    text = response.read().decode()
    html = bs4.BeautifulSoup(text, 'html.parser')
    shoes = html.find_all("div", attrs={"class", "tile browse-tile"})
    name = []
    for shoe in shoes:
        name.append(shoe.find('a').get('href'))
print(name)

name1 = ['/adidas-yeezy-boost-700-bright-blue', '/air-jordan-5-retro-raging-bulls-red-2021', '/air-jordan-1-retro-high-hyper-royal-smoke-grey', '/nike-sb-dunk-high-hawaii', '/air-jordan-1-retro-high-white-university-blue-black', '/nike-dunk-low-green-glow-w', '/adidas-yeezy-boost-350-v2-core-black-red-2017', '/adidas-yeezy-boost-350-v2-carbon', '/converse-chuck-taylor-all-star-70s-hi-off-white', '/nike-blazer-mid-77-vintage-white-black', '/new-balance-550-aime-leon-dore-white-navy-red', '/adidas-yeezy-500-utility-black', '/air-jordan-1-retro-high-bio-hack', '/air-jordan-1-retro-high-pine-green-black', '/air-jordan-1-retro-high-unc-chicago-leather-w', '/air-jordan-11-retro-playoffs-2019', '/adidas-yeezy-700-v3-arzareth', '/nike-air-max-95-og-neon-2020', '/nike-air-max-90-infrared-2020', '/air-jordan-12-retro-black-dark-concord', '/nike-dunk-high-black-varsity-maize', '/nike-air-rubber-dunk-off-white-unc', '/air-jordan-1-retro-high-tie-dye-w', '/air-jordan-5-retro-fire-red-silver-tongue-2020', '/adidas-yeezy-700-v3-alvah', '/jordan-11-retro-space-jams-2016', '/air-jordan-1-retro-high-travis-scott', '/nike-dunk-high-michigan-2020', '/nike-dunk-low-brazil-2020', '/air-jordan-1-retro-high-shadow-2018', '/nike-dunk-low-sp-syracuse', '/air-jordan-1-retro-black-blue-2017', '/adidas-yeezy-boost-350-v2-yecher', '/new-balance-550-aime-leon-dore-natural-green', '/nike-air-max-270-react-travis-scott', '/nike-air-force-1-low-travis-scott-cactus-jack', '/air-jordan-1-low-black-toe', '/adidas-yeezy-boost-350-v2-sulfur', '/nike-dunk-low-sp-kentucky', '/nike-sb-dunk-low-travis-scott']
name2 = ['/air-jordan-1-retro-high-85-varsity-red', '/jordan-1-retro-bred-2016', '/air-jordan-1-retro-high-patent-gold-toe', '/adidas-yeezy-boost-700-v3-azael', '/air-jordan-1-mid-se-fearless-edison-chen', '/nike-air-max-1-anniversary-red-2017-restock', '/air-jordan-1-retro-low-travis-scott', '/nike-air-max-1-anniversary-royal-2017-restock', '/air-jordan-1-low-sail-university-gold-black', '/nike-air-force-1-low-travis-scott-sail', '/nike-air-fear-of-god-moccasin-black', '/adidas-yeezy-boost-700-v2-static', '/air-jordan-6-retro-aleali-may-w', '/air-jordan-1-mid-se-lakers', '/nike-air-force-1-low-canvas-travis-scott-af100', '/nike-air-max-97-country-camo-germany', '/nike-nike-air-max-1-sport-royal-2017', '/air-max-1-patta-5th-anniv-green', '/nike-air-max-97-country-camo-uk', '/vans-og-sk8-hi-odd-future-donut', '/vans-sk8-hi-fog', '/lebron-1-air-zoom-generation-wheat-all-star', '/jordan-1-og-chicago-1985', '/vans-authentic-supreme-blue-checker-logo', '/air-max-95-stash', '/air-max-1-animal-pack', '/air-max-1-b-atmos-viotech', '/jordan-10-og-sacramento-kings', '/jordan-3-retro-oregon-ducks-pit-crew-black', '/louis-vuitton-don-kanye-red', '/air-max-1-ams-parra-amsterdam', '/air-jordan-11-retro-low-legend-blue', '/air-jordan-1-mid-gym-red-black-white', '/air-jordan-6-retro-carmine-2020', '/nike-air-force-1-low-white-07', '/air-jordan-11-retro-low-legend-blue-gs', '/air-jordan-1-high-zoom-cmft-aleali-may-w', '/air-jordan-1-mid-dutch-green-w', '/air-jordan-4-retro-university-blue', '/yeezy-slide-resin']
name3 = ['/nike-air-force-1-low-supreme-box-logo-white', '/air-jordan-5-retro-raging-bulls-red-2021-gs', '/yeezy-slide-core', '/nike-dunk-low-retro-white-black-2021', '/nike-air-max-95-nrg-lebron-lakers', '/air-jordan-4-retro-taupe-haze', '/adidas-yeezy-700-v3-kyanite', '/adidas-yeezy-slide-pure', '/adidas-yeezy-boost-350-v2-ash-pearl-2021', '/adidas-yeezy-foam-rnnr-sand', '/air-jordan-1-mid-barely-rose-w', '/nike-dunk-low-photon-dust-w', '/nike-air-max-90-nrg-bacon-2021', '/adidas-campus-80s-south-park-towelie', '/air-jordan-5-retro-white-stealth-2021', '/air-jordan-1-mid-paint-drip-gs', '/air-jordan-1-mid-carbon-fiber', '/nike-dunk-low-retro-black-hyper-cobalt-2021', '/air-jordan-1-retro-high-hyper-royal-smoke-grey-gs', '/air-jordan-3-retro-a-ma-maniere-w', '/nike-lebron-18-low-atmos-cherry-blossom', '/air-jordan-3-retro-georgetown-2021', '/nike-dunk-low-retro-medium-grey-varsity-red-2021', '/nike-air-griffey-max-1-jackie-robinson', '/air-jordan-1-retro-high-light-army', '/air-jordan-11-retro-black-clear', '/nike-dunk-low-orange-pearl', '/air-jordan-1-retro-high-silver-toe-w', '/nike-air-force-1-low-supreme-box-logo-black', '/nike-dunk-high-syracuse-2021', '/air-jordan-1-mid-banned-2020', '/air-jordan-1-retro-high-white-university-blue-black-gs', '/adidas-yeezy-boost-350-v2-zyon', '/air-jordan-1-retro-high-dark-mocha', '/air-jordan-1-mid-se-all-star-2021-gs', '/air-jordan-1-mid-arctic-orange-gs', '/adidas-zx-8000-sean-wotherspoon-superearth', '/air-jordan-4-retro-fire-red-2020', '/nike-dunk-low-white-black-2021-w', '/adidas-yeezy-foam-rnnr-mxt-moon-gray']
name4 = ['/air-jordan-12-retro-low-easter-2021', '/nike-kobe-6-protro-grinch', '/nike-air-force-1-07-black-black', '/air-jordan-1-mid-black-royal-tumbled-leather', '/nike-dunk-high-dark-sulfur-w', '/nike-air-max-1-clot-kiss-of-death-2021', '/nike-dunk-low-retro-white-black-gs', '/air-jordan-1-retro-high-university-blue-td', '/adidas-yeezy-boost-350-v2-israfil', '/adidas-yeezy-boost-350-v2-white-core-black-red', '/air-jordan-1-retro-high-white-black-volt-university-gold', '/air-jordan-1-retro-high-black-metallic-gold-2020', '/nike-air-vapormax-plus-triple-black', '/air-jordan-3-retro-cool-grey-2021', '/air-jordan-1-mid-triple-white-2-2020', '/air-jordan-1-mid-se-purple', '/air-jordan-6-retro-carmine-2020-gs', '/nike-space-hippie-01-anthracite-volt', '/air-jordan-1-mid-signal-blue', '/adidas-yeezy-boost-350-v2-sand-taupe', '/air-jordan-1-low-light-smoke-grey', '/air-jordan-1-mid-banned-2020-gs', '/air-jordan-1-mid-purple-aqua', '/nike-dunk-low-coast', '/air-jordan-1-retro-high-court-purple-white', '/adidas-yeezy-boost-700-v2-cream', '/nike-air-max-97-white-wolf-grey', '/air-jordan-1-retro-high-light-smoke-grey', '/air-jordan-5-retro-raging-bulls-red-2021-td', '/air-jordan-1-retro-high-og-university-blue-ps', '/adidas-forum-84-high-eric-emanuel-mcdonalds-all-american', '/nike-dunk-high-retro-white-vast-grey-2021', '/air-jordan-1-mid-hyper-royal-gs', '/nike-air-force-1-low-rose-white', '/air-jordan-1-low-se-arctic-punch', '/air-jordan-1-retro-high-black-game-royal', '/air-jordan-1-mid-university-gold', '/nike-air-force-1-low-white-gum', '/air-jordan-1-high-zoom-cmft-stadium-green', '/air-jordan-1-low-court-purple-white']
name5 = ['/adidas-yeezy-700-v3-clay-brown', '/nike-air-max-97-black-white-anthricite', '/air-jordan-4-retro-taupe-haze-gs', '/air-jordan-5-retro-what-the', '/air-jordan-1-retro-high-lucky-green-w', '/nike-air-griffey-max-1-varsity-royal-2021', '/air-jordan-5-retro-raging-bulls-red-2021-ps', '/air-jordan-4-retro-university-blue-gs', '/air-jordan-1-mid-chicago-toe', '/air-jordan-1-mid-purple-aqua-gs', '/nike-sb-dunk-low-wasted-youth', '/nike-air-huarache-scream-green-2021', '/reebok-answer-iv-og-20th-anniversary', '/air-jordan-5-retro-white-stealth-2021-gs', '/air-jordan-1-mid-black-gym-red-gs', '/nike-dunk-high-sail-pale-ivory-w', '/adidas-yeezy-boost-350-v2-ash-stone', '/nike-sb-dunk-low-club-58-gulf', '/air-jordan-1-low-white-university-red-black', '/converse-chuck-taylor-all-star-70s-hi-comme-des-garcons-play-black', '/nike-dunk-high-se-all-star-2021', '/nike-space-hippie-03-healing-jade', '/air-jordan-1-low-reverse-bred', '/air-jordan-1-mid-black-chile-red-white', '/air-jordan-1-low-se-all-star-2021', '/air-jordan-1-mid-igloo', '/air-jordan-11-retro-black-clear-gs', '/air-jordan-9-retro-change-the-world-w', '/adidas-yeezy-boost-350-v2-ash-blue', '/nike-dunk-low-retro-hyper-cobalt-gs', '/air-jordan-12-retro-reverse-flu-game', '/air-jordan-13-retro-gym-red-flint-grey', '/adidas-yeezy-boost-350-v2-natural', '/adidas-yeezy-boost-380-covellite', '/air-jordan-1-mid-white-shadow', '/air-jordan-3-retro-varsity-royal-cement', '/nike-air-max-1-evolution-of-icons', '/air-jordan-9-retro-dark-charcoal-university-gold', '/nike-air-force-1-sage-low-triple-white-w', '/air-jordan-1-low-purple-magenta-w']
name6 = ['/air-jordan-1-low-triple-white-tumbled-leather', '/nike-react-phantom-run-flyknit-2-white-pure-platinum-w', '/air-jordan-1-zoom-air-cmft-psg-paris-saint-germain', '/air-jordan-1-mid-university-gold-gs', '/air-jordan-6-retro-travis-scott-british-khaki', '/nike-dunk-low-college-navy-grey-w', '/adidas-yeezy-boost-350-v2-cinder', '/air-jordan-1-low-paint-drip-gs', '/air-jordan-3-retro-georgetown-2021-gs', '/adidas-forum-low-bad-bunny-pink', '/nike-air-max-95-nyc-taxi', '/nike-dunk-low-sb-celadon', '/air-jordan-1-low-university-blue-black', '/air-jordan-1-low-arctic-punch-gs', '/nike-air-vapormax-plus-white', '/nike-dunk-high-syracuse-w-2021', '/crocs-classic-clog-justin-bieber-drew-house-lavender', '/air-jordan-1-low-white-gs', '/air-jordan-1-zoom-cmft-easter-w', '/air-jordan-12-retro-arctic-punch-gs', '/air-jordan-1-mid-triple-white-gs', '/nike-air-force-1-low-popcorn', '/adidas-yeezy-desert-boot-taupe-blue', '/air-jordan-13-retro-black-hyper-royal', '/nike-air-vapormax-flyknit-3-oreo', '/air-jordan-5-retro-off-white-sail', '/air-jordan-4-retro-fire-red-2020-gs', '/nike-air-vapormax-flyknit-3-white-pure-platinum', '/air-jordan-1-mid-peach-mocha-w', '/nike-air-structure-og-white-neo-teal', '/air-jordan-1-retro-high-midnight-navy-2020', '/nike-air-force-1-low-white-2018-w', '/air-jordan-1-mid-canyon-rust-w', '/air-jordan-6-retro-dmp-2020', '/nike-kobe-5-protro-bruce-lee', '/air-jordan-5-retro-anthracite', '/adidas-yeezy-450-cloud-white', '/nike-dunk-low-retro-white-black-ps', '/air-jordan-1-mid-apricot-orange-w', '/nike-sb-dunk-low-wasted-youth-special-box']
name7 = ['/air-jordan-13-retro-flint-2020', '/air-jordan-11-retro-low-concord-bred', '/air-jordan-13-retro-starfish', '/nike-air-huarache-escape', '/nike-dunk-low-medium-curry', '/air-jordan-1-low-prm-smoke-grey-elephant', '/air-jordan-1-retro-high-fearless-unc-chicago', '/adidas-yeezy-boost-350-v2-cream-white', '/air-jordan-1-retro-high-85-neutral-grey', '/nike-air-more-uptempo-black-white-2016', '/nike-sb-dunk-low-pink-pig', '/nike-air-max-pre-day-light-liquid-lime', '/nike-dunk-high-sp-syracuse-gs-2021', '/air-jordan-12-retro-stone-blue', '/air-jordan-1-mid-se-union-royal', '/nike-air-force-1-07-qs-love-letter', '/nike-air-force-1-low-valentines-day-2021', '/adidas-yeezy-700-v3-safflower', '/adidas-yeezy-boost-350-v2-desert-sage', '/air-jordan-1-retro-high-bio-hack-gs', '/air-jordan-1-retro-high-j-balvin', '/air-jordan-1-mid-signal-blue-gs', '/air-jordan-1-mid-gym-red-black-w', '/air-jordan-1-mid-chicago-black-toe-gs', '/air-jordan-1-mid-chicago-2020', '/air-jordan-1-mid-se-turf-orange', '/adidas-ultra-boost-40-dna-triple-black', '/adidas-yeezy-boost-350-v2-black', '/adidas-yeezy-wave-runner-700-solid-grey', '/nike-sb-dunk-low-court-purple', '/air-jordan-4-retro-starfish-w', '/nike-kobe-6-protro-challenge-red', '/nike-air-force-1-low-paisley-swoosh', '/air-jordan-4-retro-off-white-sail-w', '/air-jordan-1-retro-high-dark-mocha-gs', '/yeezy-slide-bone', '/nike-air-force-1-low-triple-red', '/nike-dunk-high-ambush-active-fuchsia', '/air-jordan-1-mid-barely-orange-w', '/nike-dunk-low-retro-medium-grey-varsity-red-unlv-gs']
name8 = ['/nike-air-vapormax-exeter-edition', '/air-jordan-12-retro-black-university-gold', '/nike-air-force-1-low-stussy-black', '/adidas-yeezy-boost-380-onyx', '/air-jordan-13-retro-white-lucky-green', '/adidas-ultra-boost-40-dna-white', '/air-jordan-5-retro-alternate-bel-air', '/air-jordan-1-low-game-royal', '/air-jordan-6-retro-black-infrared-2019', '/air-jordan-9-retro-dark-charcoal-university-gold-gs', '/nike-air-force-1-07-white-black-pebbled-leather', '/nike-react-phantom-run-flyknit-2-black-barely-volt-w', '/nike-dunk-low-veneer-2020', '/air-jordan-5-retro-top-3', '/air-jordan-3-retro-fragment', '/nike-air-max-90-valentines-day-2021-w', '/nike-air-force-1-low-rose-pink', '/nike-air-more-uptempo-hoops-pack-17', '/nike-air-force-1-06-triple-white-td', '/nike-dunk-low-disrupt-summit-white-ghost-w', '/nike-air-vapormax-flyknit-3-triple-black', '/air-jordan-1-retro-high-shattered-backboard-3', '/air-jordan-1-low-reverse-bred-gs', '/nike-air-max-1-strawberry-lemonade-2020', '/nike-dunk-high-prm-dark-russet', '/nike-air-max-90-surplus-cargo-khaki', '/air-jordan-1-low-crimson-tint-gs', '/air-jordan-5-retro-alternate-grape', '/air-jordan-3-retro-se-fire-red-2020', '/nike-air-vapormax-evo-nrg-air-max-day-mashup-2021', '/adidas-ultra-boost-2021-triple-black', '/nike-react-phantom-run-flyknit-2-college-navy', '/air-jordan-1-retro-high-co-japan-neutral-grey', '/air-jordan-1-retro-high-white-black-volt-university-gold-gs', '/nike-air-max-90-30th-anniversary-white-particle-grey-volt', '/air-jordan-11-retro-jubilee-w', '/nike-dunk-low-retro-white-black-td', '/air-jordan-1-low-reverse-bred-pebbled-swoosh', '/nike-air-force-1-type-sail', '/nike-react-phantom-run-flyknit-2-black-white-w']
name9 = ['/nike-lebron-8-hardwood-classic-2021', '/air-jordan-1-mid-white-shadow-gs', '/air-jordan-1-retro-high-unc-leather', '/nike-dunk-low-se-easter-w', '/nike-air-vapormax-plus-white-red', '/air-jordan-1-retro-high-satin-snake-chicago-w', '/air-jordan-1-retro-high-black-game-royal-gs', '/adidas-yeezy-boost-350-v2-yecheil', '/air-jordan-3-retro-se-fire-red', '/adidas-yeezy-boost-380-calcite-glow', '/converse-chuck-taylor-all-star-70s-hi-comme-des-garcons-play-white', '/air-jordan-1-mid-white-black-chile-red-gs', '/nike-dunk-low-sp-city-market', '/nike-air-max-270-triple-black', '/nike-air-force-1-low-st-patricks-day-2021', '/nike-air-max-cb-94-white-varsity-purple', '/nike-dunk-low-spartan-green-gs', '/air-jordan-1-high-zoom-cmft-stadium-green-w', '/nike-kyrie-4-low-keep-sue-fresh', '/adidas-yeezy-boost-350-v2-yeezreel', '/air-jordan-1-mid-metallic-gold-black-white', '/nike-blazer-mid-77-popcorn', '/air-jordan-1-mid-paint-drip-ps', '/nike-dunk-low-disrupt-sea-glass-w', '/air-jordan-why-not-zer04-marathon', '/adidas-yeezy-boost-350-v2-citrin', '/adidas-yeezy-boost-350-v2-cloud-white', '/nike-air-force-1-gtx-black', '/air-jordan-1-mid-dia-de-los-muertos', '/adidas-nmd-hu-pharrell-black', '/nike-blazer-mid-readymade-black', '/nike-air-force-1-experimental-black', '/air-jordan-11-retro-low-legend-blue-td', '/air-jordan-5-retro-se-oregon', '/air-jordan-4-retro-black-cat-2020', '/air-jordan-4-retro-union-off-noir', '/air-jordan-4-retro-bred-2019', '/converse-run-star-hike-hi-black-white-gum', '/nike-air-force-1-lx-tear-away-white-w', '/nike-overbreak-sp-undercover-sail']
name10 = ['/nike-air-max-90-recraft-wolf-grey', '/nike-air-vapormax-2020-flyknit-oreo', '/nike-dunk-low-disrupt-siren-red-w', '/nike-dunk-low-free-99-black', '/air-jordan-xxxv-clot-terra-cotta', '/nike-air-force-1-experimental-usps', '/crocs-classic-clog-justin-bieber', '/air-jordan-1-retro-high-satin-black-toe-w', '/nike-sb-dunk-high-carpet-company', '/nike-air-max-90-surplus-desert-camo', '/nike-dunk-low-disrupt-sail-desert-sand-w', '/nike-air-max-plus-wolf-grey', '/nike-air-max-90-white-barely-rose-w', '/nike-air-more-uptempo-rayguns', '/adidas-yeezy-500-high-frosted-blue', '/nike-react-vision-barely-volt-laser-crimson', '/nike-vaporwaffle-sacai-tan-navy', '/air-jordan-1-mid-chicago-2020-gs', '/air-jordan-1-low-gym-red-white', '/adidas-yeezy-boost-380-pepper', '/air-jordan-1-retro-high-black-metallic-gold-2020-gs', '/nike-air-max-95-gunsmoke-pink-foam', '/nike-dunk-high-sp-varsity-purple-w', '/nike-air-force-1-low-white-2014-gs', '/nike-air-vapormax-plus-triple-red', '/reebok-pump-omni-zone-ii-dee-brown-2021', '/air-jordan-3-retro-cool-grey-2021-gs', '/air-jordan-1-mid-se-south-beach', '/new-balance-550-white-grey', '/adidas-nmd-hu-pharrell-human-race-triple-black-pack', '/new-balance-1300-aime-leon-dore-green', '/nike-react-phantom-run-flyknit-2-vast-grey-fire-pink-team-orange-w', '/a-bathing-ape-bape-sta-low-white-abc-camo-green', '/air-jordan-13-retro-black-hyper-royal-gs', '/air-jordan-4-retro-psg-paris-saint-germain', '/air-jordan-1-retro-high-light-smoke-grey-gs', '/air-jordan-1-mid-se-black-dark-beetroot-w', '/adidas-yeezy-boost-350-v2-tail-light', '/nike-dunk-low-ceramic-2020', '/air-jordan-9-retro-university-blue']
name11 = ['/air-jordan-11-retro-concord-2018', '/nike-air-huarache-stussy-desert-oak-2021', '/nike-air-max-97-undftd-black-militia-green', '/new-balance-990v5-grey', '/nike-dunk-high-vast-grey-gs', '/nike-air-max-plus-white', '/air-jordan-1-low-university-gold', '/adidas-nmd-hu-pharrell-pink', '/converse-chuck-taylor-all-star-70-kim-jones-natural', '/air-jordan-3-retro-laser-orange-w', '/air-jordan-1-low-white-camo', '/air-jordan-1-mid-metallic-gold-black-white-gs', '/adidas-yeezy-qntm-frozen-blue', '/nike-overbreak-sp-undercover-black', '/nike-air-force-1-low-miami-nights', '/air-jordan-1-mid-laser-orange-w', '/nike-air-griffey-max-1-white-freshwater-2021-gs', '/nike-air-force-1-low-shadow-sail-barely-green-w', '/nike-air-max-pre-day-summit-white', '/air-jordan-4-retro-se-neon', '/adidas-yeezy-boost-350-v2-earth', '/nike-air-rubber-dunk-off-white-green-strike', '/nike-dunk-high-pro-green', '/converse-chuck-taylor-all-star-70s-hi-comme-des-garcons-play-multi-heart-white', '/air-jordan-14-retro-low-clot-terra-blush', '/air-jordan-1-low-se-black-metallic-silver-w', '/air-jordan-1-retro-high-silver-toe-td', '/nike-air-max-90-flyleather-ruohan-wang', '/nike-offline-anthracite-electro-orange', '/nike-air-more-uptempo-white-varsity-red-outline', '/air-jordan-1-high-switch-peach', '/nike-space-hippie-01-wolf-grey-volt', '/adidas-superstar-sean-wotherspoon-superearth', '/air-jordan-3-retro-black-court-purple', '/nike-air-max-90-lx-90s-dancefloor-green-w', '/nike-blazer-mid-77-vintage-racer-blue', '/adidas-ultra-boost-20-triple-black', '/nike-air-max-1-live-together-play-together', '/air-jordan-1-retro-high-silver-toe-ps', '/nike-air-max-97-gold-medal']
name12 = ['/air-jordan-1-high-zoom-air-cmft-canyon-rust-w', '/nike-air-foamposite-pro-volt-2021', '/adidas-ozweego-pale-nude', '/nike-air-max-tailwind-v-skepta', '/nike-air-max-90-fried-chicken', '/kobe-6-protro-playoff-pack-white-del-sol', '/air-jordan-4-retro-white-court-purple', '/nike-air-force-1-low-white-black-2020', '/crocs-classic-clog-grateful-dead-x-chinatown-market', '/air-jordan-6-retro-travis-scott', '/air-jordan-1-mid-laser-blue', '/nike-dunk-high-sp-white-grey', '/air-jordan-3-retro-black-cement-2018', '/nike-space-hippie-03-grey-volt', '/nike-air-vapormax-flyknit-3-black-snakeskin', '/nike-air-max-90-christmas-sweater-2020', '/air-jordan-1-high-zoom-air-cmft-london', '/nike-dunk-high-sail-team-red-w', '/adidas-ultra-boost-2021-triple-white', '/nike-air-vapormax-flyknit-3-phantom-laser-fuchsia-w', '/nike-air-max-plus-color-flip-pack-black', '/adidas-forum-84-low-crew-green', '/a-bathing-ape-bape-sta-low-white-abc-camo-blue', '/nike-air-force-1-low-g-dragon-peaceminusone-para-noise-20', '/nike-air-force-1-low-orange-skeleton', '/nike-sb-dunk-low-j-pack-chicago', '/adidas-yeezy-boost-350-v2-lundmark', '/air-huarache-black-black-white', '/adidas-nmd-r1-triple-black-2019', '/nike-air-max-270-react-plum-chalk-stone-mauve-w', '/nike-air-force-1-high-white', '/air-jordan-1-low-canyon-rust-w', '/nike-air-vapormax-2020-flyknit-black-dark-grey', '/air-jordan-11-retro-low-legend-blue-ps', '/new-balance-992-grey', '/air-jordan-1-mid-multi-patent-w', '/nike-waffle-racer-off-white-black-w', '/nike-air-max-97-slime-halloween-2020', '/nike-air-max-1-lemonade-2020', '/nike-blazer-mid-77-white-celestine-blue']
name13 = ['/adidas-nmd-hu-pharrell-extra-eye-white', '/nike-dunk-low-hyper-cobalt-ps', '/nike-blazer-mid-77-vintage-pine-green', '/nike-air-vapormax-2020-flyknit-obsidian', '/nike-air-max-90-michigan-navy', '/adidas-yeezy-boost-380-mist', '/air-jordan-1-mid-unc-w', '/nike-sb-dunk-low-atmos-elephant', '/air-jordan-1-mid-se-union-black-toe', '/air-jordan-1-mid-turf-orange-gs', '/nike-air-max-plus-triple-black', '/nike-air-force-1-shadow-triple-white-w', '/air-jordan-4-retro-golf-white-cement', '/converse-chuck-taylor-all-star-70s-ox-comme-des-garcons-play-black', '/nike-dunk-low-disrupt-pale-ivory-black-w', '/nike-air-max-1-lv8-obsidian', '/adidas-ultra-boost-dna-lego', '/new-balance-1300-aime-leon-dore-pink', '/nike-vaporwaffle-sacai-tour-yellow-stadium-green', '/air-jordan-1-mid-grey-camo', '/nike-blazer-mid-77-white-black-w', '/nike-air-force-1-low-stussy-fossil', '/air-jordan-1-mid-black-white-w', '/air-jordan-1-mid-85-gs', '/air-jordan-1-low-black-blue-white', '/nike-air-max-95-kim-jones-black-total-orange', '/nike-air-max-plus-3-laser-blue', '/reebok-club-c-cardi-dynamic-pink-w', '/nike-air-max-90-prm-light-smoke-grey', '/nike-air-max-ff-720-summit-white-w', '/adidas-yeezy-500-enflame', '/nike-dunk-low-samba-2020', '/air-jordan-1-retro-high-black-gym-red-black', '/adidas-yeezy-boost-700-mnvn-triple-black', '/nike-vaporwaffle-sacai-villain-red-neptune-green', '/nike-sb-dunk-low-medicom-toy-2020', '/air-jordan-1-mid-white-black-light-arctic-pink-gs', '/yeezy-slide-soot', '/nike-sb-dunk-low-street-hawker', '/air-jordan-5-retro-what-the-gs']
name14 = ['/air-jordan-1-retro-high-black-gym-red', '/nike-waffle-racer-off-white-vivid-sky-w', '/nike-kobe-5-protro-5-rings', '/nike-air-max-97-undftd-black-volt', '/adidas-yeezy-boost-350-v2-blue-tint', '/nike-air-max-90-halloween-2020', '/nike-react-phantom-run-flyknit-2-red-orbit', '/nike-sb-dunk-high-baroque-brown-vegan-leather', '/nike-air-max-90-jacquard-court-purple', '/adidas-ultra-boost-2021-core-black', '/adidas-yeezy-qntm-sea-teal', '/nike-kobe-4-protro-undefeated-san-antonio-spurs', '/air-jordan-1-low-gym-red-black-pebbled-gs', '/nike-blazer-mid-77-sunset-pulse-w', '/nike-air-vapormax-plus-barely-volt-w', '/air-jordan-1-mid-light-smoke-grey', '/air-jordan-1-retro-high-zoom-black-green', '/nike-air-max-270-white-black', '/adidas-yeezy-boost-350-v2-sesame', '/air-jordan-1-retro-high-turbo-green', '/air-jordan-6-retro-carmine-2020-td', '/air-jordan-1-high-zoom-air-cmft-black-monarch', '/nike-air-vapormax-2020-flyknit-summit-white', '/adidas-yeezy-qntm-basketball', '/nike-air-max-270-triple-red', '/new-balance-550-white-red', '/nike-air-tuned-max-celery', '/nike-dunk-low-sp-orange-pearl-td', '/nike-space-hippie-01-wolf-grey', '/nike-air-max-96-ii-white-midnight-navy', '/air-jordan-12-retro-black-university-gold-gs', '/adidas-yeezy-boost-350-v2-linen', '/air-jordan-1-retro-high-pine-green-black-gs', '/nike-dunk-low-st-johns-2020', '/nike-dunk-high-bodega-fauna-brown', '/nike-air-griffey-max-1-white-freshwater-2021', '/nike-air-force-1-flyknit-2-white-pure-platinum', '/adidas-yeezy-boost-350-v2-butter', '/nike-air-max-90-st-patricks-day-2021', '/nike-air-max-90-recraft-royal']
name15 = ['/adidas-ultra-4d-triple-black', '/adidas-ultra-boost-4-0-triple-white-w', '/nike-blazer-mid-77-vintage-white', '/air-jordan-6-retro-carmine-2020-ps', '/air-jordan-5-retro-white-stealth-2021-td', '/nike-shox-tl-black-metallic-hematite-w', '/nike-sb-dunk-high-pro-orange-label-smoke-grey', '/nike-vaporwaffle-sacai-purple-orange', '/a-bathing-ape-bape-sta-low-white-abc-camo-pink', '/nike-vaporwaffle-sacai-black-white', '/adidas-ultra-boost-4-0-running-white', '/air-jordan-11-retro-low-ie-black-cement', '/nike-sb-dunk-low-ben-jerrys-chunky-dunky', '/adidas-yzy-qntm', '/air-jordan-1-retro-high-court-purple-white-gs', '/air-jordan-1-mid-sisterhood-w', '/adidas-yeezy-boost-350-v2-semi-frozen-yellow', '/adidas-ultra-boost-all-white', '/nike-dunk-low-off-white-pine-green', '/adidas-nmd-r1-black-gum-2018', '/nike-air-force-1-low-raygun', '/nike-air-max-90-metallic-gold-2020-w', '/nike-air-vapormax-flyknit-3-black-gs', '/nike-dunk-high-se-all-star-2021-gs', '/air-max-1-dark-teal-green', '/nike-dunk-low-sp-orange-pearl-ps', '/air-jordan-1-mid-black-siren-red-w', '/nike-air-max-90-caramel-w', '/converse-chuck-taylor-all-star-70-kim-jones-black', '/air-jordan-1-low-arctic-pink-gum-w', '/air-jordan-1-mid-green-toe-gs', '/air-jordan-4-retro-union-guava-ice', '/nike-sb-dunk-low-sean-cliver', '/air-jordan-12-low-se-superbowl-lv', '/crocs-duet-max-clog-post-malone', '/nike-sb-dunk-low-vx1000', '/air-jordan-1-high-zoom-air-cmft-pink-glaze-w', '/nike-air-max-90-surplus-black', '/nike-air-max-90-slide-black-white', '/nike-mamba-focus-metallic-gold']
name16 = ['/nike-adapt-bb-2-mag-eu-charger', '/nike-zoom-pegasus-turbo-2-neptune-green', '/nike-dunk-low-white-bone-peach-aqua-gs', '/nike-air-max-270-white-gum', '/nike-sb-janoski-g-white-black', '/air-jordan-1-mid-se-all-star-2021-ps', '/a-bathing-ape-bapesta-low-white-grey', '/air-jordan-11-retro-low-concord-bred-gs', '/air-jordan-3-retro-unc-2020', '/nike-vaporwaffle-sacai-sport-fuchsia-game-royal', '/air-jordan-5-retro-off-white-black', '/air-jordan-4-retro-what-the', '/nike-sb-dunk-low-wheat-2020', '/air-jordan-1-mid-dynamic-yellow-floral-gs', '/nike-kobe-5-protro-lakers', '/air-jordan-1-retro-high-off-white-university-blue', '/adidas-yeezy-boost-380-hylte', '/adidas-yzy-qntm-ophani', '/adidas-yeezy-boost-350-v2-beluga-2-0', '/jordan-4-retro-white-cement-2016', '/new-balance-327-white-moonbeam-w', '/nike-air-force-1-mid-white-07', '/air-jordan-1-low-university-blue-black-gs', '/air-huarache-white-platinum', '/air-jordan-1-mid-triple-black', '/nike-air-force-1-07-se-love-for-all-w', '/air-jordan-6-retro-sd-triple-black-w', '/adidas-nmd-r1-v2-dazzle-camo-white', '/air-jordan-9-retro-dark-charcoal-university-gold-ps', '/nike-lebron-7-los-angeles-dodgers', '/nike-air-max-270-barely-rose-w', '/adidas-futurecraft-4d-2021-black-green', '/nike-air-max-plus-city-special-atl-w', '/nike-dunk-low-hyper-cobalt-td', '/nike-kobe-4-protro-undefeated-black-mamba', '/nike-shox-nova-white-red-w', '/nike-air-force-1-low-pixel-sail-coconut-milk-w', '/air-jordan-5-retro-white-stealth-2021-ps', '/air-jordan-1-low-crimson-tint', '/adidas-forum-84-low-orbit-grey']
name17 = ['/nike-air-force-1-lx-tear-away-sail-w', '/nike-air-force-1-shadow-white-glacier-blue-ghost-w', '/nike-dunk-low-lemon-wash', '/air-jordan-1-mid-royal-2019', '/nike-air-force-1-low-south-korea-2020', '/air-jordan-1-retro-high-black-hyper-pink', '/crocs-duet-max-2-post-malone-black', '/air-jordan-4-retro-cool-grey-2019', '/air-jordan-5-retro-low-chinese-new-year-2021', '/nike-kobe-5-protro-bruce-lee-alternate', '/nike-shox-tl-white-metallic-silver', '/nike-air-vapormax-flyknit-3-triple-black-w', '/adidas-nmd-r1-white-gum-2018', '/nike-air-max-90-laser-blue-2020', '/nike-air-max-270-white-black-w', '/nike-sb-dunk-low-supreme-barkroot-brown', '/nike-lebron-17-what-the', '/air-jordan-ma2-future-beginnings', '/nike-sb-dunk-low-supreme-mean-green', '/air-jordan-5-golf-low-wolf-grey', '/adidas-zx-10000-simpsons-krusty-burger', '/adidas-ultra-boost-10-dna-cookies-and-cream', '/nike-air-vapormax-plus-live-together-play-together', '/air-jordan-1-low-se-all-star-gs-2021', '/nike-kyrie-6-bruce-lee', '/air-jordan-14-retro-black-gym-red', '/air-jordan-13-retro-flint-2020-gs', '/adidas-yeezy-boost-700-mauve', '/nike-ld-waffle-sacai-white-nylon', '/air-jordan-4-retro-white-university-red', '/air-jordan-1-low-light-smoke-grey-gs', '/air-jordan-11-retro-playoffs-2019-gs', '/nike-air-max-1-pine-green-2020', '/nike-sb-dunk-low-grateful-dead-bears-yellow', '/air-jordan-1-retro-high-shattered-backboard-3-gs', '/nike-air-max-1-anniversary-orange-2020', '/nike-dunk-low-disrupt-black-white-w', '/air-jordan-9-retro-university-blue-gs', '/air-jordan-1-low-black-guava-ice-w', '/air-jordan-4-retro-se-deep-ocean']
name18 = ['/nike-kobe-5-protro-undefeated-what-if-pack', '/nike-space-hippie-01-black-wheat', '/nike-air-force-1-low-flax-2019', '/nike-air-max-1-recycled-white', '/nike-air-max-90-trail-team-gold', '/gucci-rubber-slides-red-green', '/air-jordan-1-mid-arctic-pink-black-gs', '/nike-kobe-5-protro-chaos', '/nike-blazer-mid-77-raygun', '/air-jordan-1-mid-se-particle-beige-w', '/nike-air-max-95-triple-black-2020', '/converse-chuck-taylor-all-star-70-hi-carhartt-hamilton-brown', '/air-jordan-1-mid-pink-shadow', '/nike-air-zoom-pegasus-36-trail-gyakusou-yellow', '/nike-react-phantom-run-flyknit-2-white-black', '/nike-blazer-mid-77-vintage-zig-zag', '/nike-air-force-1-low-pacific-blue', '/adidas-forum-84-high-orbit-grey', '/nike-air-max-97-white-pine-green', '/nike-air-force-1-low-gold-link-zebra', '/adidas-harden-vol-5-solar-yellow', '/nike-air-max-90-triple-red-2020', '/air-jordan-1-low-university-gold-black-gs', '/nike-lebron-18-low-lebronald-palmer', '/nike-air-vapormax-evo-evolution-of-icons-w', '/air-jordan-1-low-shadow', '/air-jordan-11-retro-low-white-concord-w', '/air-jordan-1-retro-high-zoom-white-racer-blue', '/nike-sb-dunk-low-pro-blue-fury', '/nike-sb-dunk-high-concepts-turdunken', '/air-jordan-1-mid-se-purple-gs', '/air-jordan-1-mid-familia-gs', '/nike-dunk-high-ambush-black-white', '/air-jordan-1-low-court-purple-white-gs', '/adidas-yeezy-boost-350-v2-clay', '/nike-blazer-mid-77-sketch-white-black', '/air-jordan-1-mid-black-racer-blue-white-gs', '/air-jordan-1-mid-se-white-black-red-spruce-gs', '/nike-kobe-5-protro-big-stage-parade-pe', '/nike-kobe-5-protro-eybl-forest-green-2020']
name19 = ['/nike-air-max-90-recycled-canvas', '/nike-sb-dunk-low-supreme-hyper-royal', '/nike-air-max-270-black-white', '/nike-air-max-97-triple-black', '/nike-air-max-97-black-white', '/nike-lebron-17-low-titan', '/air-force-1-low-white-pine-green', '/air-jordan-6-retro-tinker', '/puma-suede-atmos-staple', '/nike-air-max-plus-usa-white-red', '/air-jordan-why-not-zer04-graffiti', '/air-jordan-6-retro-hare', '/adidas-yeezy-boost-700-inertia', '/air-jordan-1-retro-high-unc-patent-w', '/nike-air-max-90-duck-camo-orange', '/air-jordan-1-retro-high-space-hippie', '/air-jordan-1-mid-bred-toe', '/air-jordan-1-mid-se-usa', '/nike-dunk-low-off-white-university-red', '/adidas-yeezy-boost-700-sun', '/nike-air-rubber-dunk-off-white-university-gold', '/nike-kybrid-s2-best-of', '/air-jordan-1-mid-se-black-white-multi-color-w', '/jordan-11-retro-legend-blue-2014', '/nike-killshot-2-j-crew-sail-midnight-navy', '/converse-chuck-taylor-all-star-70s-hi-comme-des-garcons-play-multi-heart-green', '/air-jordan-1-retro-high-fearless-metallic-rose-gold-w', '/adidas-harden-vol-5-futurenatural', '/new-balance-327-casablanca-black-logo', '/nike-mx-720-818-black', '/nike-air-force-1-low-pixel-desert-sand-w', '/nike-air-max-90-black-wolf-grey', '/nike-air-max-1-remix', '/air-jordan-1-high-zoom-air-cmft-black-chile-red', '/nike-lebron-18-james-gang', '/nike-air-max-90-recraft-triple-white', '/air-max-1-martian-sunrise', '/nike-air-vapormax-2020-flyknit-deep-royal-blue-multi-color', '/nike-air-max-90-recraft-triple-black', '/nike-kobe-4-protro-undefeated-phoenix-suns']
name20 = ['/nike-air-force-1-low-shadow-sunset-pulse-w', '/nike-free-run-trail-neutral-grey-summit-white', '/adidas-yeezy-boost-350-v2-cloud-white-infant', '/adidas-ultra-boost-2021-white-solar-yellow', '/adidas-niteball-cream-white', '/air-jordan-1-centre-court-white-university-red', '/new-balance-327-moonbeam-classic-burgundy-w', '/air-jordan-14-retro-white-hyper-royal', '/air-jordan-1-low-unc-w', '/air-jordan-1-mid-green-toe', '/air-jordan-1-retro-high-bloodline', '/nike-ld-waffle-sacai-black-nylon', '/nike-air-max-2-light-atmos', '/nike-dunk-low-sp-university-orange-marine-2020', '/air-jordan-6-retro-washed-denim', '/nike-air-force-1-type-white', '/air-jordan-3-retro-animal-pack', '/puma-rs-dreamer-j-cole-black', '/air-jordan-3-retro-se-fire-red-gs', '/air-jordan-1-mid-laser-orange-black-w', '/air-jordan-11-adapt-white', '/air-jordan-1-mid-magenta-w', '/air-jordan-1-low-laser-blue', '/nike-sb-dunk-low-sashiko', '/nike-sb-dunk-low-supreme-black', '/nike-blazer-mid-77-dia-de-los-muertos', '/nike-space-hippie-03-vast-grey-hyper-crimson', '/nike-air-vapormax-flyknit-3-pure-platinum-w', '/air-jordan-12-retro-fiba-2019', '/converse-chuck-taylor-all-star-70s-ox-comme-des-garcons-play-white', '/nike-air-vapormax-flyknit-3-oreo-w', '/nike-benassi-stussy-off-noir', '/nike-air-max-97-undefeated-ucla', '/nike-kd-13-aunt-pearl', '/nike-air-presto-off-white-white-2018', '/nike-blazer-mid-77-brick-red', '/nike-air-force-1-pixel-white-w', '/air-jordan-1-low-multi-color-black-toe-w', '/air-jordan-3-retro-tinker-hatfield', '/adidas-rivalry-hi-star-wars-chewbacca']
name21 = ['/air-jordan-1-low-laser-blue-black', '/air-jordan-5-retro-low-golf-black-metallic', '/nike-dbreak-type-dia-de-los-muertos', '/air-jordan-1-low-black-active-fuchsia', '/nike-cortez-basic-forrest-gump-2019', '/nike-air-force-1-low-worldwide-white-blue-fury-black', '/new-balance-327-casablanca', '/nike-p-6000-triple-white-w', '/nike-air-force-1-07-coconut-milk-w', '/adidas-terrex-free-hiker-gtx-black', '/nike-air-force-1-07-midnight-navy', '/nike-cosmic-unity-space-hippie', '/nike-kobe-4-protro-undefeated-los-angeles-lakers', '/converse-run-star-hike-high-made-with-love-valentines-day-2021', '/air-jordan-1-low-white-w', '/air-jordan-1-low-white-camo-gs', '/nike-air-vapormax-evo-wolf-grey', '/nike-react-vision-white-light-smoke-grey', '/adidas-ultra-boost-40-dna-grey-three', '/new-balance-550-white-multicolor', '/air-jordan-1-mid-crimson-tint-toe', '/nike-air-force-1-low-lv8-double-swoosh-light-armory-blue', '/nike-air-force-1-experimental-suns', '/adidas-ultra-boost-2021-carbon-active-teal', '/nike-air-vapormax-plus-orlando-magic', '/air-jordan-1-mid-igloo-gs', '/adidas-zx-8000-highsnobiety', '/nike-air-max-90-reverse-duck-camo-2020', '/air-jordan-4-retro-winter', '/air-jordan-12-retro-black-dark-concord-gs', '/air-jordan-1-mid-nike-hoops', '/air-jordan-12-retro-reverse-flu-game-gs', '/nike-react-element-87-blue-chill-solar-red', '/nike-sb-dunk-high-invert-celtics', '/nike-sb-dunk-low-frame-skate-habibi', '/air-jordan-1-retro-high-phantom-gym-red', '/air-jordan-1-retro-high-satin-snake-chicago-ps', '/adidas-ultra4d-black-purple', '/adidas-ultra-boost-4-triple-black', '/air-jordan-3-retro-true-blue-2016']

name = name1+name2+name3+name4+name5+name6+name7+name8+name9+name10\
       +name11+name12+name13+name14+name15+name16+name17+name18+name19+name20


# take yeezy as an example
# 正常的筛选过程
shoes_yeezy = []
for names in name:
    if "yeezy" in names:
        shoes_yeezy.append(names)
# 这里储存的是全部的yeezy的名字
# 因为可能爬取不了名字了可以直接从这里用起
# 1
shoes_yeezy = ['/adidas-yeezy-boost-700-bright-blue', '/adidas-yeezy-boost-350-v2-core-black-red-2017', '/adidas-yeezy-boost-350-v2-carbon', '/adidas-yeezy-500-utility-black', '/adidas-yeezy-700-v3-arzareth', '/adidas-yeezy-700-v3-alvah', '/adidas-yeezy-boost-350-v2-yecher', '/adidas-yeezy-boost-350-v2-sulfur', '/adidas-yeezy-boost-700-v3-azael', '/adidas-yeezy-boost-700-v2-static', '/yeezy-slide-resin', '/yeezy-slide-core', '/adidas-yeezy-700-v3-kyanite', '/adidas-yeezy-slide-pure', '/adidas-yeezy-boost-350-v2-ash-pearl-2021', '/adidas-yeezy-foam-rnnr-sand', '/adidas-yeezy-boost-350-v2-zyon', '/adidas-yeezy-foam-rnnr-mxt-moon-gray', '/adidas-yeezy-boost-350-v2-israfil', '/adidas-yeezy-boost-350-v2-white-core-black-red', '/adidas-yeezy-boost-350-v2-sand-taupe', '/adidas-yeezy-boost-700-v2-cream', '/adidas-yeezy-700-v3-clay-brown', '/adidas-yeezy-boost-350-v2-ash-stone', '/adidas-yeezy-boost-350-v2-ash-blue', '/adidas-yeezy-boost-350-v2-natural', '/adidas-yeezy-boost-380-covellite', '/adidas-yeezy-boost-350-v2-cinder', '/adidas-yeezy-desert-boot-taupe-blue', '/adidas-yeezy-450-cloud-white', '/adidas-yeezy-boost-350-v2-cream-white', '/adidas-yeezy-700-v3-safflower', '/adidas-yeezy-boost-350-v2-desert-sage', '/adidas-yeezy-boost-350-v2-black', '/adidas-yeezy-wave-runner-700-solid-grey', '/yeezy-slide-bone', '/adidas-yeezy-boost-380-onyx', '/adidas-yeezy-boost-350-v2-yecheil', '/adidas-yeezy-boost-380-calcite-glow', '/adidas-yeezy-boost-350-v2-yeezreel', '/adidas-yeezy-boost-350-v2-citrin', '/adidas-yeezy-boost-350-v2-cloud-white', '/adidas-yeezy-500-high-frosted-blue', '/adidas-yeezy-boost-380-pepper', '/adidas-yeezy-boost-350-v2-tail-light', '/adidas-yeezy-qntm-frozen-blue', '/adidas-yeezy-boost-350-v2-earth', '/adidas-yeezy-boost-350-v2-lundmark', '/adidas-yeezy-boost-380-mist', '/adidas-yeezy-500-enflame', '/adidas-yeezy-boost-700-mnvn-triple-black', '/yeezy-slide-soot', '/adidas-yeezy-boost-350-v2-blue-tint', '/adidas-yeezy-qntm-sea-teal', '/adidas-yeezy-boost-350-v2-sesame', '/adidas-yeezy-qntm-basketball', '/adidas-yeezy-boost-350-v2-linen', '/adidas-yeezy-boost-350-v2-butter', '/adidas-yeezy-boost-350-v2-semi-frozen-yellow', '/adidas-yeezy-boost-380-hylte', '/adidas-yeezy-boost-350-v2-beluga-2-0', '/adidas-yeezy-boost-700-mauve', '/adidas-yeezy-boost-350-v2-clay', '/adidas-yeezy-boost-700-inertia', '/adidas-yeezy-boost-700-sun', '/adidas-yeezy-boost-350-v2-cloud-white-infant']

# 2
information = []

# 3
# 对应名字的鞋子的数据
def get_static(names):
    ssl._create_default_https_context = ssl._create_unverified_context
    headers = {
        # 浏览器
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'}

    # 网址 (url)
    url = "https://stockx.com" + names
    req = urllib.request.Request(url=url, headers=headers)
    response = urllib.request.urlopen(req)
    # html
    text = response.read().decode()
    html = bs4.BeautifulSoup(text, 'html.parser')
    # 每天的价格
    content = html.find_all("div", class_="inset css-8atqhb")
    # sys.setdfaultencoding('utf8')
    ls_size = []
    ls_price = []
    for shoes in content:
        size = shoes.contents[0].text
        price = shoes.contents[1].text
        ls_size.append(size)
        ls_price.append(price)

    name_index = "".join(filter(str.isalnum, names)).upper()
    df = pd.DataFrame(ls_price, index=ls_size, columns=[name_index])
    df = df.T
    return df


# 读取所有yeezy的数据
for i in range(1, len(shoes_yeezy)):
    df = get_static(shoes_yeezy[i])
    information.append(df)
# 有时候会读到重复数据，用来去除column的重复
for i in range(0,len(information)):
    information[i] = information[i].loc[:, ~information[i].columns.duplicated()]
# 读取所有的存在于已有数据里的鞋码
all_size = []
for i in range(0,len(information)):
    all_size.extend(information[i].columns)
# 利用set的特性来去除重复项
all_size = list(set(all_size))
# 以下为不同报错情况的对应解决方案
# all_size.remove(0)
# all_size.sort()

# 全部整理成拥有所有的鞋码来保证列数相等，没有数据的一个是本来的'Bid'一个是填充的数字0
for i in range(0,len(information)):
    for size1 in all_size:
        if size1 not in information[i].columns:
            information[i].insert(information[i].shape[1],size1,0)

# 转换成dataframe
all_data = pd.concat(information)

# change columns name to fit number
c = list(all_data.columns)
for i in range(1,len(c)):
    c[i] = re.findall(r"\d+\.?\d*",c[i])
for i in range(1,len(c)):
    all_data = all_data.rename(columns={all_data.columns[i]:c[i][0]})

all_data.to_excel("/Users/songyijin/Desktop/data_SX.xlsx")

#all_data = all_data.rename(columns={'index':'shoes_name'})
#all_data = all_data.set_index('shoes_name')
#my_style = '''
#color: red; background-color: white
#'''
#test.style.applymap(lambda x: my_style,subset=test.index)